Qt browser (#1686)
* Add in some additional integration code to help with demos not working properly.

* v8 bug fixs

* Qt browser 1st pass

* merge code

* use source code instead of prebuild for qt

* build qt from srouce on windows

* SVG corrupted cached file bug unit test (#1695)

* Adding BANNER to [build.sh] + test for SVG corrupted cached files bug.

* Adding [test_imagecacheSVG.cpp] to cmake

* rtRemote services support (#1688)

* rtRemote services support

* permissions file updates

* rtRemote service updates

* font fix (#1696)

* Ignore CORS checks for localhost requests (#1699)

* Increase travis timeout value (#1705)

* Increase travis timeout value

* Update execute_linux.sh

* few travis cleanups (#1689)

* few travis cleanups

* Update Spark.cpp

* Update Spark.cpp

* Update execute_linux.sh

* Update execute_linux.sh

* downloading and launch performance updates (#1706)

* downloading improvements and metrics

* downloading updates

* lowered log levels of some debug statements

* removing debug prints during load

* removed excess debug prints

* update to 1.5.0.0 (#1707)

* ability to create additional contexts (#1712)

* initial commit

* ability to create additional contexts

* XRE-13676 : Optimus application couldn't launch due to error (#1697)

* XRE-13676 : Optimus application couldn't launch due to error doesn't give the enough information of the cause

* XRE-13676 : Optimus application couldn't launch due to error

Update error message

* XRE-13676 : Optimus application couldn't launch due to error

Update error message - removing '{}'

* Input: Fix leaked directory resource (#1700)

* optimus updates for memory management (#1701)

* Adding support for #RGB, #RRGGBB, and Web Named colors (#1663)

* Adding support for #RGB, #RRGGBB, and Web Named colors

* Adding <string.h>

* Adding [A] optional alpha to #RGB[A] and #RRGGBB[AA] support

* Remove errant 'extern' to nanosvg

* Resolving 'unused' CI build warning as error

* Revert change

* Bugs

* - Adding 'cssColors' capability entry

* adding 'test_pxWebColors_v1.js'

* Internal method naming ...

* Changing to internal naming

* Changed toLower() to toLowerAscii() for clarity - per comment on GH

* Fixed dirty rect issue with hidden and animated obejcts (#1694)

* AntiAliasing for FBO textures on macOS

* reverted changes

* reverted

* dirty rect CPU optimization

* Moves screen coordingates calculation for child objects into parent pxobject:update

* removed context dependency in dirty rect process

* Removed special case context push and pop for dirty rects

* Fixed answer.js issue

* Reverted recent dirty rect changes and added fix for answer.js

* revert

* Fixed dirty rect issue with hidden and animated obejcts

* Fixed dirty rect issue with hidden and animated obejcts

* Fixed dirty rect issue with hidden and animated obejcts

* Fixed dirty rect bug

* Fixed dirty rect bug

* Fixed dirty rect issue

* Mainly fixed texture piles with dirty rect

* clean up

* clean up

* Fixed all flickering issues so far

* Fixed scene.create object which doesnt go through update

* Fixed textbox update issue

* Fixed textbox update issue

* Fixed pxImage pxImage9 pxImageA update issue and setting up dirty flag on update

* cleanup

* Merged PR1571

* Merged PR1571

* Fixed atp getDirtyRect

* Fixed pxTextBox onscreen height and width

* setIsDirty function in pxScene2d

* Added missed def

* Fixed errors in build

* Fixed errors in build

* Fixed build error

* Fixed build error

* Added check for gEnabledDirtyRect

* Added check for gEnabledDirtyRect

* Renames

* use of markDirty

* Cleanup

* CleanUp

* markDirty on resource is ready

* Fixed picturepiles2.js issue

* cleanup

* cleanup

* cleanup

* Update shell.js

* clean up sandbox and wrap some callbacks in try..catch (#1703)

* remove unnecessary items from sandbox

* wrap end-user callbacks in try..catch for http events

* a test for http end after close

* add license for a new file supportfiles/http5s.js

* Increase travis timeout value

* Update execute_linux.sh

* for unit tests check ls returns nonzero instread of 1

* changes for spark log identification (#1687)

* changes for spark log identification

* changes for spark log identification

* extend ci linux time

* Update execute_linux.sh

* added Console api

* Update console_wrap.js

* Update console_wrap.js

* remove rtRemote (#1714)

* remove rtRemote

* remove rtRemote

* Update rtSettings.cpp

* Marking overlapping child objects dirty if parent is dirty (#1722)

* AntiAliasing for FBO textures on macOS

* reverted changes

* reverted

* dirty rect CPU optimization

* Moves screen coordingates calculation for child objects into parent pxobject:update

* removed context dependency in dirty rect process

* Removed special case context push and pop for dirty rects

* Fixed answer.js issue

* Reverted recent dirty rect changes and added fix for answer.js

* revert

* Added pxRect::isOverlapping to check if child is affected on parent dirty

* Break out [pxObject] from [pxScene2d]. Remove [pxPath]...  Tidy up. (#1726)

* Rename [animation] to [pxAnimation]. Break out [pxObject].  Tidy up.

* Changed [animation] >> [pxAnimation]

* Warnings about misleading indents. Fixed

* Removed old code

* Minor change

* Minor Change

* Adding missing virtuals.

* Backing out [pxAnimation] rename ... reverting to [animation]

* Missed one.  Reverted [pxAnimation] to [animation]

* update screencapture_jar test (www.sparkui.org, canned image) (#1720)

* remove pxObject's matrix props (#1717)

* remove pxObject's matrix props

* fix old typo

* use updated test_pxScene2d

* readd changes to a moved pxObject

* put qt to spark on draw

* null pointer check for coverity fix (#1732)

* build fix: (#1719)

/home/npoltorapavlo/pxCore/examples/pxScene2d/src/pxTextBox.cpp:277:52: error: no matching function for call to ‘pxMax(float&, int)’
     return pxMax(mw, abs(bounds->x2()-bounds->x1()));
                                                    ^
/home/npoltorapavlo/pxCore/examples/pxScene2d/src/glut/pxContextUtils.cpp:21:37: warning: unused parameter ‘id’ [-Wunused-parameter]
 pxError deleteInternalGLContext(int id)
                                     ^

* Move to use sparkui.org (#1713)

* temporarily point to px-apps for coverflow

* use new names from sparkui.org

* Move to use www.sparkui.org

* Set useBaseURI to false

* Change pxscene.org to sparkui.org

* More changes of pxscene.org to sparkui.org

* use sparkui.org for coverflow

* temporarily point to px-apps for coverflow

* use new names from sparkui.org

* Move to use www.sparkui.org

* Set useBaseURI to false

* Change pxscene.org to sparkui.org

* More changes of pxscene.org to sparkui.org

* use sparkui.org for coverflow

* Small change to test Url

* add new test from PR #1663

* Try again with same url

* add logging

* Revert "add logging"

This reverts commit 3af93a3b3128cb447f7b4edf19e68930007f0534.

* Fixes issue where MASK was not respecting Alpha of parent object (#1709)

* AntiAliasing for FBO textures on macOS

* reverted changes

* reverted

* dirty rect CPU optimization

* Moves screen coordingates calculation for child objects into parent pxobject:update

* removed context dependency in dirty rect process

* Removed special case context push and pop for dirty rects

* Fixed answer.js issue

* Reverted recent dirty rect changes and added fix for answer.js

* revert

* Fixed alpha for masking object

* added atp for alpha testing on objects

* merge

* changes for about.js window re-arrangement after resize (#1724)

* metrics for downloads (#1739)

* metrics for downloads

* decode metrics and report results on promise ready

* type cleanup

* font resource support for metrics

* include setup time in metrics

* indicate if loaded from cache or not

* adding source type for files and archive

* updates for cached content

* added a new api for shared contexts and references (#1742)

*  added a new api for shared contexts and references (#1744)

* added a new api for shared contexts and references

* added a new api for shared contexts and references update

* Mutex lock/unlock is not required during reaching from cache. DELIA-3… (#1743)

* Mutex lock/unlock is not required during reaching from cache. DELIA-33016 need this fix.

* Mutex lock/unlock is not required during reaching from cache. The issue reported in DELIA-33016 got fixed with this fix.

* changes for node compile optimization and inspector selection  (#1747)

* changes for node compile optimization and inspector selection

* changes for node compile optimization and inspector selection

* Update node_contextify.cc

* Update node.gyp

* avoid remove listener if url not changed (#1750)

* avoid setting resource url again

* Update pxImage.cpp

* Update pxImage.cpp

* Update pxImage.cpp

* Update pxImage.cpp

* Update pxImage.cpp

* XRE2-1791 (#1737)

* XRE2-1791

* XRE2-1791 / 2

* XRE2-1791 / 3

* XRE2-1791 / 3

* XRE2-1791 / 4

* XRE2-1791 / 4

* XRE2-1791 / 4

* XRE2-1791 / 4

* XRE2-1791 / 4

*  XRE2-1791. Removed rtl() and encapsulated logging level translation

*  XRE2-1791. Indentation

* XRE2-1791 upd

* shared context support for egl (#1751)

* initial commit

* updates

* updates

* updates

* thread safety support

* threading updates

* update

* removing test for removed api

*  mac build updates for node (#1749)

* mac build updates

* mac build updates

* update to 1.6.0.0 (#1753)

* fix for mips contexts (#1756)

* add pxBrowser render support

* enabling metrics for few scenarios (#1757)

* enabling metrics for few scenarios

* enabling metrics for few scenarios

* Update pxContextUtils.cpp

* Update pxContextUtils.cpp

* Update pxScene2d.cpp

* Update pxScene2d.cpp

* Update pxResource.cpp

* Update pxResource.cpp

* avoid double downloads for image9 (#1758)

* avoid double downloads for image9

* Update pxImage9.cpp

* Update pxImage9.cpp

* Update pxImage9.cpp

* Enhanced Drag and Drop support (macOS) (#1754)

* Enhanced Drag and Drop support

* Adding Drag'n'Drop TEXT support ... via new insertText() method

* Corrected some behaviors

* Correction to URL from native

* Fixes to Edit.js

* No focus - FILE drop - behavior

* Fix leak

* Tidy up WS

* Fix crash

* Adding drag&drop highlight to textbox

* Changes per PR comments

* update to 1.6.0.1 (#1759)

* fix qt browser build error on windows

* fixed windows  qt render

* Fix Black Frame on Input box + ws removal (#1762)

* few travis cleanups (#1738)

* added changes for detecting travis crash on exit

* Update execute_osx.sh

* genarate suppresions

* Update execute_osx.sh

* fix one-time random travis leaks

* fix one-time random travis leaks

* Update Spark.cpp

* Update Spark.cpp

* Update Spark.cpp

* Update Spark.cpp

* Update Spark.cpp

* Update Spark.cpp

* Update Spark.cpp

* Update execute_osx.sh

* Update execute_osx.sh

* Update execute_osx.sh

* Update Spark.cpp

* Update Spark.cpp

* Update execute_osx.sh

* Update Spark.cpp

* Update rtThreadPoolNative.cpp

* Update rtThreadPoolNative.cpp

* Update Spark.cpp

* Update rtThreadPoolNative.cpp

* Update rtThreadPoolNative.cpp

* Update execute_osx.sh

* Update rtThreadPoolNative.cpp

* Update Spark.cpp

* Update execute_osx.sh

* Update execute_osx.sh

* Update Spark.cpp

* Update Spark.cpp

* Update pxContextGL.cpp

* few travis cleanups on false leaks

* few travis cleanups on false leaks

* Update execute_linux.sh

* Update execute_osx.sh

* Update execute_osx.sh

* add windows pxContext Utils

* Adding initializer (#1766)

* increase travis max time for test execution by 5 mins (#1767)

* suspend and resume updates (#1769)

* suspend and resume updates

* updates

* Adding [test_pxColorNames.js] to TestRunner tests (#1760)

* Adding [test_pxColorNames.js] to TestRunner tests

* Fix test title.

* Added a check to see if a native app is a valid path before launching (#1765)

* Removing Z_SOLO define for zlib builds (#1770)

* Removing Z_SOLO define for zlib builds

* Revert "Removing Z_SOLO define for zlib builds"

This reverts commit 19654d79a101a4245fee95b6aeb95da6a3de14e7.

* making z_solo define change as patch

* Revert "making z_solo define change as patch"

This reverts commit 0847ae06f3b92c6d5459638547881d5b499b7a25.

* Revert "Revert "Removing Z_SOLO define for zlib builds""

This reverts commit 715488d43febc7cf86d99a35a518bf94c1e25c0d.

* Accept "200ms" type strings for animations (#1755)

* XRE2-986 URL protocol Case sensitivity in px.getFile() (#1752)

* XRE2-986 URL protocol Case sensitivity in px.getFile()

*  XRE2-986 upd 1

* DELIA-33982 : The Multimedia Keys support is added to pxCore (#1772)

* DELIA-33982 : The Multimedia Keys support is added to pxCore

Reason for change: Support TRICK PlayKeys from the Multimedia KeyBoard/Amazon Remote
Test Procedure: Test TRICK PlayKeys from the DELL Multimedia KeyBoard and Amazon Bluetooth Remote
Risks: Medium
Signed-off-by: Karunakaran A <Karunakaran_Amirthalingam@cable.comcast.com>

* DELIA-33982 : Updated the Mulimedia Key support to ESSOS and Wayland only

Signed-off-by: Karunakaran A <Karunakaran_Amirthalingam@cable.comcast.com>

* DELIA-33982 : Updated the compile time macros as per the review comment

Reason for the Change: Updated the compile time macros to individual keys that are added to this review. This way, we can ensure that the any platform that adds a support will automatically pick up the feature.

Signed-off-by: Karunakaran A <Karunakaran_Amirthalingam@cable.comcast.com>

* support for configurable thread pool size (#1774)

* support for configurable thread pool size

* support for configurable thread pool size and downloads

* resolution updates (#1775)

* resolution updates

* resolution updates

* XRE2-1555 invalid fontResource causes promise never to fire (#1768)

* XRE-1555 invalid fontResource causes promise never to fire

* XRE-1555 upd

* XRE-1555 upd

* XRE-1555 upd

* XRE-1555 upd

* XRE2-1555 updated tests.json

* Send SIGTERM to pxWayland clients instead of SIGKILL while terminating (#1776)

* Fixed rendering some chars outside text box (#1741)

* AntiAliasing for FBO textures on macOS

* reverted changes

* reverted

* dirty rect CPU optimization

* Moves screen coordingates calculation for child objects into parent pxobject:update

* removed context dependency in dirty rect process

* Removed special case context push and pop for dirty rects

* Fixed answer.js issue

* Reverted recent dirty rect changes and added fix for answer.js

* revert

* Render char outside assigned area is fixed

* avoid reporting crashes occuring due to asynchronous exit (#1782)

* avoid reporting crashes occuring due to asynchronous exit

* avoid reporting crashes occuring due to asynchronous exit

* Update execute_osx.sh

* fix for http requests created after sandbox destroy (#1771)