changes to make it work with system libraries (#700)
* make it work with system libraries

Introduces PREFER_SYSTEM_LIBRARIES option which when set to ON
prefer to use system libraries over bundled ones.

* fix compilation errors

 - remove gcc unsupported pragma,
 - correct include directory.

* update zlib library to v1.2.11 version

This fixes the following issue on macOS:
bash-3.2$ ./pxscene2dtests.sh
dyld: Symbol not found: _inflateValidate
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
  Expected in: ../../examples/pxScene2d/external/zlib/libz.1.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
./pxscene2dtests.sh: line 55: 10591 Abort trap: 6           ./pxscene2dtests