remove unused code (wayland_egl / shell_surface_listener)
Detected by the following compiler error:

pxCore/src/wayland_egl/pxWindowNative.cpp:297:1: error: missing initializer for member ‘wl_shell_surface_listener::popup_done’ [-Werror=missing-field-initializers]
 };
 ^