Revert "reverting PR 1359 (#1481)" (#1488)
* Revert "reverting PR 1359 (#1481)"

This reverts commit 44724e32e6c4504667a09137e2ad5b7741ecf5d5.

* fix 'TypeError: _this.appSandbox.importTracking[bPath].push is not a function'

* CI test for the px.import bugs