fix missing-field-initializers compilation errors
Fixes the following errors:

pxCore/src/rtScriptDuk/rtScriptDuk.cpp: In function ‘duk_ret_t duv_require(duk_context*)’:
pxCore/src/rtScriptDuk/rtScriptDuk.cpp:643:3: error: missing initializer for member ‘duv_schema_entry::checker’ [-Werror=missing-field-initializers]
   };
   ^
pxCore/src/rtScriptDuk/rtScriptDuk.cpp: In function ‘duk_ret_t duv_mod_resolve(duk_context*)’:
pxCore/src/rtScriptDuk/rtScriptDuk.cpp:740:3: error: missing initializer for member ‘duv_schema_entry::checker’ [-Werror=missing-field-initializers]
   };
   ^
pxCore/src/rtScriptDuk/rtScriptDuk.cpp: In function ‘duk_ret_t duv_mod_load(duk_context*)’:
pxCore/src/rtScriptDuk/rtScriptDuk.cpp:757:3: error: missing initializer for member ‘duv_schema_entry::checker’ [-Werror=missing-field-initializers]
   };
   ^
pxCore/src/rtScriptDuk/rtScriptDuk.cpp: In function ‘duk_ret_t duv_loadlib(duk_context*)’:
pxCore/src/rtScriptDuk/rtScriptDuk.cpp:807:3: error: missing initializer for member ‘duv_schema_entry::checker’ [-Werror=missing-field-initializers]
   };
   ^
pxCore/src/rtScriptDuk/rtScriptDuk.cpp: In function ‘duk_ret_t duv_mod_compile(duk_context*)’:
pxCore/src/rtScriptDuk/rtScriptDuk.cpp:833:3: error: missing initializer for member ‘duv_schema_entry::checker’ [-Werror=missing-field-initializers]
   };
   ^