SparkGL support (#2069)
* webgl support (#1859)

* Added initial webgl support

* added a new api for shared contexts and references (#1742)

*  added a new api for shared contexts and references (#1744)

* added a new api for shared contexts and references

* added a new api for shared contexts and references update

* shared context support for egl (#1750)

* initial commit

* updates

* updates

* updates

* thread safety support

* threading updates

* update

* removing test for removed api

* fix for mips contexts (#1756)

* updates to the new shared context api

* Added view events for the webgl view

* Enhanced triangle sample to log out some view events

* Added a todo comment

* Fixed crash when creating a Function object

* Added support for setTimeout to setup gl context

* depth support for egl

* setImmediate wrapper to setup drawing context

* Fixed a bug in clearImmediate wrapper

* A fix to make webgl scene nav more stable

* Added a variation of the triangle webgl sample

* Applied a patch to RunInThisContext

* adding the process object to sandbox

* Added a per sandbox spark module system

* exposing beginDrawing/endDrawing to global space

* Fixed crash in https ... lightning content reloads

* Clear color in new gl context

* Clearing initial framebuffer for webgl context

* fix a typo in method9ArgAndNoReturn macro

Signed-off-by: Gurdal Oruklu <gurdaloruklu@gmail.com>

* initial commit for WebGL

* fix libnode6.9 macOS compiler flags

* modified triangle2.js to use Spark's own WebGL

* merge update

* merge updates

* build fixes (#1862)

* build fixes

* build fixes

* adding edge builds (#1875)

* node updates and patches

* node updates

* updates for edge builds

* fix for edge build auto updates (#1876)

* fix onClose, fix setImmediate (#1906)

* add more modules to sandbox (#1885)

* run init.js as starting script

* run init.js as starting script

* Update test_rtnode.cpp

* Update test_rtnode.cpp

* Management of HTTP, HTTPS, WebSockets lifetimes (#1912)

* Management of HTTP, HTTPS, WebSockets lifetimes

* fix typo (https vs http, clearImmediate vs clearTimeout), better logging

* ability to get native texture id for pxTextureOffscreen (#1892) (#1921)

*  adding ability to create and expose textures of text and images objects (#1929)

* adding ability to create and expose textures of text and images

* updates

* texture creation helper api (#1931)

* rendering updates for text and images (#1933)

* Webgl fixes for linux (#1920)

* fixes for lightning++ on linux

* a fix for gl black screen

* fixed stuff which was reset during beginDrawing/endDrawing

* same fixes for triangle2.js

* minor changes for mac

* Update spark.sh

* node10 integration (#1934)

* adding node10 source code

* node-v10.5.3

* Revert "node-v10.5.3"

This reverts commit 96703c21230cbad8cdd67d11f0efea1b7a7cf8d9.

* spark changes for node10

* spark changes for node10

* remove 8.15.1 files

* remove 8.15.1 files

* Update CommDeps.cmake

* Update spark.sh

* Update leak.supp

* windows changes

* windows changes

* compatibility with node 6.9

* Update execute_linux.sh

* compatibility with node 6.9

* fix uwebsockets build locally

* fix uwebsockets build locally

* fix crash on syntax errors

* fix crash on syntax errors

* Update leak.supp

* adding qemu patch

* reduce logging (#1945)

* fix 3-box (upgrade to canvas 2.x, infinite loop fix, gl fixes) and 4-static (gl fixes) (#1943)

* local storage for Lightning++ (#1944)

* enabling inspector (#1942)

* enabling inspector

* enabling inspector

* adding node-fetch module (#1954)

* mjs support changes (#1956)

* mjs support changes

* Update pxScene2d.cpp

* Update initGL.js

* Update initGL.js

* Update initGL.js

* adding some additional node modules (#1957)

* gl header updates (#1958)

* remove the need to build with harfbuzz (#1959)

* adding ability to flip images vertically when created (#1960)

* adding ability to flip images

* image udpates

* image updates

* image updates

* script updates (#1965)

* startup optimizations (#1967)

* added some missing webGL functions (#1969)

* changes for fixing path issues on js file under webgl (#1961)

* Update execute_linux.sh

* Update execute_linux.sh

* changes for running js file

* changes for fixing path issues on js file under webgl

* optimizations (#1972)

* optimization

* updates

* image resource flip updates (#1973)

* optimization

* updates

* image resource flip updates

* expose localStorage, a fix for non-mjs files (#1963)

* cleanup initGL (#1978)

* cleanup initGL

* Update initGL.js

* Update execute_linux.sh

* Update execute_linux.sh

* Update initGL.js

* Update initGL.js

* changes for fixing node6,node10 compatibility (#1990)

* fix for crash on exception on async execution (#1993)

* fixing issues seen with running apps remotely (#1994)

* fixing issues seen with running apps remotely

* Update initGL.js

* code cleanup (#1995)

* Effects merge (#1998)

* Adding [shaderResource] (#1908)

* Adding [shaderResource]

* Changed log level

* Adding files missed in merge/pick

* Define needed...

* Warnings...

* More warnings.

* Updates ...

* Minor fix

* Refactor / Tidy

* More tidying...

* Updates

* Naming convention for "internal" classes

* Update pxMatrix4T.h

* Missed removal of [pxShaderEffect.cpp] ... fixed

* Errant include of "pxShaderEffect.h" - now removed

* Refactor and Simplification

* Removed errant [skipTransform} ...

* Inlining...

* Refactor and Tidy up

* Tidy up unused code

* Tidy

* Revert name change

* Remove dead code

* Narrow scope via 'static' ...

* Simplification

* Refactoring...

* References !

* Adding CI test for [ shaderResource ]

* Fix warnings

* Name change to avoid conflicts

* Refactor to isolate code better

* Grrrrr... "#define ANIMATION_ROTATE_XYZ"

* Grrrr 2 ... "#define ANIMATION_ROTATE_XYZ"

* Grrr 3 - "#define ANIMATION_ROTATE_XYZ"

* Only one "#define ANIMATION_ROTATE_XYZ" ...

* Bug

* Changed dependency

* Refactor program and "use()"

* Tidy up

* Adding tests ... some refactoring

* CodeCov Test updates

* Additional tests ...

* Updates

* Additional testing changes

* Project changes + bug fix

* Updates to tests

* Missed a bug in merge.

* Comment out Archive support (for now)

* "off by one" bug in copy from rtString to rtData

* Refactoring and refinement.

* Fixes to google tests

* Unused params

* Adding flush() to API

* Save/Restore uniforms

* Permit "no uniforms" in config.

* Updated CPP unit test.  Fixed comment.

* Removed glException class throw/catch. Fix Reject

* Fix warnings

* Update per Review comments

* Missed a change.  Added Warning.

* Removed errant AddRef() calls

* Adding appropriate AddRef() calls.

* Minor edit

* ANIMATION_ROTATE_XYZ  related

* Adding include.

* Class name change

* More detail.

* Useful comment

* Avoid flicker on RT shaders

* Allow a little more time to test.

* Refactor use of shaders and FBO's

* Removed unnecessary 'flush()' api

* Remove AddRef() ... possible leak

* Fix for "FILE://" or "file://" prefixed URL's (#1984)

* Fix for "FILE://" or "file://" prefixed URL's

* Typo fix

*  Typo ... should have been Lowercase + Uppercase (#1986)

* Fix for "FILE://" or "file://" prefixed URL's

* Typo fix

* Typo ... should have been Lowercase + Uppercase

* AddRef() - Fix for compailation failed case. (#1989)

* AddRef() - Fix for compailation failed case.

* Revert .shaders version 2 -> 1

* Quieter

* Fixes for Shader Compilation failures

* Changes per PR review.

* Fix for Data/File mix permutations

* updates

* code coverage improvement for eventloop and windownative (#1870)

*  bootstrap (#1991)

* refactoring of json util functions

* bootstrap

* extension should include dot

* create app with options

* support non-gl: URLs in initGL

* optimization

* fix broken CI, revert some changes

* CI test, a fix for .spark?... urls

* create ready promise in constructor

* change useBaseURI to a proper value

* memory leak fix

* default to transparent background for sparkgl apps (#2007)

* support for spark keys and q downloads with query params (#2010)

* image flip updates and ability to read query parameters (#2012)

* image flip updates

* support to read query parameters

* fix overriding of file descriptors on spawned processes (#2014)

* Implemented fillText() and fillStyle() with color, font and pixelSize support (#2020)

refactored pxTextPaint as pxTextCanvas

Updates to pxTextCanvas, width() support

function stubs for the functions used in Lightning

updated pxTextCanvas with all props and method stubs for Lightning++. Includes the test script

moved some method definitions from pxTextCanvas.h to pxTextCanvas.cpp

moved some method definitions from pxFont.h to pxFont.cpp

fillStyle() now accepts ARGB color notation; fixed a crash when getting shadowBlur value

new property: label

Fixes

canvas size quick fix
translate property
removed shadow/hightlighting from pxTextCanvas (now dervied from pxText)
removed excessive debug info (almost)

debug info

* fix leaks (#2017)

* gl cleanup on pxWebGL destroy

* gl.delete fucntions support

* clean up memory when initGL destroys, remove hacks

* clean up global when initGL destroys

* clean bootStrapCache (leak), fix accidential global variables, delete all from sandbox

* remove old code

* change log level

* do not keep duplicate ids

* delete unique elements with std::find

* fix a leak in pxContextGL

* clean renderbuffer

* Fix for text displacement on pxTextCanvas (#2021)

* export lightning app exports via api; allow create bootstrap apps w/o options (#2025)

* video support (#2027)

* an object to support video playback (#1816)

* fix for black screen on mojave

* Video Support (#2024)

* XRE2-2164: Intergrate AAMP & depending libraries

Reason for change:  AAMP player & depending libraries required to make AAMP as the primary player of Spark
Test Procedure: Make sure that building the Spark for Linux & Mac & make contains the necessary libraries of AAMP
Risks: Low

Signed-off-by: Vinod Damodaran <vinod_damodaran@comcast.com>

* XRE2-2099: Support AAMP playback on SPARK

Reason for change: Added AAMP support in SPARK.
Test Procedure: Play js script with scene type 'video'
Risks: Medium

Signed-off-by: Vinod Damodaran <vinod_damodaran@comcast.com>

* build.sh updates

* Add URL Query Parameters to Options for Lightning Apps (#2023)

* fix for hangs (#2018)

* fix for hangs

* Update pxScene2d.cpp

* Update pxScene2d.cpp

* Update pxScene2d.cpp

* adding missing license headers (#2029)

* support file: URLs and relative to them (#2030)

* support file:, http URLs and relative to them

* fix ci scripts...

* disabling passing parameters into options (#2037)

* fix Error: Cannot find module 'ws' (#2039)

* pxTextCanvas improvements (#2038)

pxTextCanvas textAlignment and textBaseline support.
Allowed negative x and y coords in fillText() and fillRect().
Clipping is on by default to resemple HTML Canvas.
globalAlpha property

* adding a default api object for gl apps (#2040)

* disabling passing parameters into options

* adding a default api object for gl apps

* adding a default api object for gl apps

* test with remote externals (#2041)

* test with built externals

* test with built externals

* cleanups

* cleanups

* Webgl on windows (#2028)

* updated readme

* linked openssl lib

* linked openssl lib

* switch to loadArchive in initGL to enable caching (#2045)

* use externals artifacts from remote (#2049)

* new change test

* new change test

* Update .travis.yml

* Update .travis.yml

* Test

* Test

* Test

* Test

* Test

* Tt

* Tt

* Tt

* few updates

* few updates

* Update .travis.yml

* Update .travis.yml

* Update after_script.sh

* Update after_script.sh

* Update build_linux.sh

* Update tests.json

* Update .travis.yml

* Remove jpeg dylib

* Avoid printing logs on success execution

* Update execute_linux.sh

* Update tests.json

* Few updates

* fix cron failures for osx (#2052)

* Update build_osx.sh

* Update .travis.yml

* Update build_osx.sh

* Update build_osx.sh

* Update build_osx.sh

* Added support for byte range curl download(RDK-24363). (#1939) (#2055)

* Added support for byyte range curl download(RDK-24363).

* Added byte curl download support.

Added trim, toString methods in rtString.

* Added byte curl download support.

Added trim, toString methods in rtString.

* Added byte curl download support.

Added trim, toString methods in rtString.

* Added byte curl download support.

Added trim, toString methods in rtString.

* pxTextCanvas: support for CutSx, CutSy, CutEx, CutEy, fontStyle in Lightning++ (#2048)

* pxTextCanvas: support for CutSx, CutSy, CutEx, CutEy props in Lightning++

* fontStyle support for pxFont; fixed a Windows build issue

* Windows compatibility fixes

* One more Windows compatibility fix

* fontStyle coercion in pxFont

* Refactored for better backward compatibility; improved coercion detection

* Revert "pxTextCanvas: support for CutSx, CutSy, CutEx, CutEy, fontStyle in Lightning++ (#2048)" (#2057)

This reverts commit 4d93600e95881979c9bb2a8ca7f1a56db87aeade.

* Revert "Revert "pxTextCanvas: support for CutSx, CutSy, CutEx, CutEy, fontStyle in Lightning++ (#2048)" (#2057)" (#2058)

This reverts commit 4b8cba2b34f092d332ffd2f6944da73e3616e007.

* Yet another backward compatibility fix and (again) improved coercion … (#2059)

* Yet another backward compatibility fix and (again) improved coercion detection

* fontStyle support for downloaded fonts

* Moved a comment to the appropriate place

* gzip for rtHttpRequest (#2056)

* Improve Spark fetch performance

* don't update node-fetch to 2.6.0 (same speed)

* pass sparkHttp like other webgl functions

* make compression default

* Added user configurable curl options (#2031)

* Mutex lock/unlock is not required during reaching from cache. (#2043)

* remove one line

* updates for edge builds

* more edge build updates

* updates

* updates for node

* prevent promise rejection on download processing (#2061)

* prevent promise rejection on download processing

* Update pxResource.h

* Update pxResource.h

* build updates

* build updates

* update to tests

* build script updates

* build script updates

* build script updates

* install script updates

* pick changes from revert a4a55d9 (#20)

* pick http_wrap.js from _webgl branch

* changes for switching to node6.9.0 (#1867)

* changes for switching to node6.9.0

* changes for switching to node6.9.0

* Update http_wrap.js

* Update http_wrap.js

* pick changes from revert a4a55d98be

* pick changes from revert a4a55d98be

* pick changes from revert a4a55d98be

* pick changes from revert a4a55d98be

* pick changes from revert a4a55d98be

* pick changes from revert a4a55d98be

* pick changes from revert a4a55d98be

* pick changes from revert a4a55d98be

* pick changes from revert a4a55d98be

* pick changes from revert a4a55d98be

* pick changes from revert a4a55d98be

* pick changes from revert a4a55d98be

* pick changes from revert a4a55d98be

* pick changes from revert a4a55d98be

* pick changes from revert a4a55d98be

* pick changes from revert a4a55d98be

* fix for mac unittests gif failure (#19)

* gif build error debug

* gif build error debug

* Update tests.json

* set external gif preference to off by default

* ensure a safe copy is given to javascript

* cleanup

* updates

* copy support

* Windows build fixes