fix 'unused-result' compilation error (#908)
Fixes the following issue:
src/rtScriptNode/rtScriptNode.cpp:404:46: error: ignoring return value of 'char* getcwd(char*, size_t)', declared with attribute warn_unused_result [-Werror=unused-result]
|        getcwd(currentPath,sizeof(currentPath));
                                               ^