fix compilation errors -Werror=unused-variable
Fixes the following errors:

src/rtScriptDuk/rtScriptDuk.cpp:286:21: error: ‘exec_argv’ defined but not used [-Werror=unused-variable]
 static const char** exec_argv;
                     ^~~~~~~~~
src/rtScriptDuk/rtScriptDuk.cpp:285:12: error: ‘exec_argc’ defined but not used [-Werror=unused-variable]
 static int exec_argc;
            ^~~~~~~~~
cc1plus: all warnings being treated as errors

pxCore/src/rtScriptDuk/rtObjectWrapper.cpp:354:19: error: unused variable ‘obj_idx’ [-Werror=unused-variable]
         duk_idx_t obj_idx = duk_push_object(ctx);
                   ^~~~~~~
pxCore/src/rtScriptDuk/rtObjectWrapper.cpp: At global scope:
pxCore/src/rtScriptDuk/rtObjectWrapper.cpp:15:20: error: ‘kPropLength’ defined but not used [-Werror=unused-variable]
 static const char* kPropLength = "length";
                    ^~~~~~~~~~~
pxCore/src/rtScriptDuk/rtObjectWrapper.cpp:13:20: error: ‘kClassName’ defined but not used [-Werror=unused-variable]
 static const char* kClassName   = "rtObject";
                    ^~~~~~~~~~

pxCore/src/rtScriptDuk/rtFunctionWrapper.cpp:6:20: error: ‘kClassName’ defined but not used [-Werror=unused-variable]
 static const char* kClassName = "Function";
                    ^~~~~~~~~~
pxCore/src/rtScriptDuk/rtObjectWrapper.cpp:354:19: error: unused variable ‘obj_idx’ [-Werror=unused-variable]
         duk_idx_t obj_idx = duk_push_object(ctx);
                   ^~~~~~~
src/rtScriptDuk/rtObjectWrapper.cpp: At global scope:
src/rtScriptDuk/rtObjectWrapper.cpp:15:20: error: ‘kPropLength’ defined but not used [-Werror=unused-variable]
 static const char* kPropLength = "length";
                    ^~~~~~~~~~~
src/rtScriptDuk/rtObjectWrapper.cpp:13:20: error: ‘kClassName’ defined but not used [-Werror=unused-variable]
 static const char* kClassName   = "rtObject";
                    ^~~~~~~~~~
src/rtScriptNode/rtWrapperUtils.cpp:22:18: error: ‘sCurrentSceneThread’ defined but not used [-Werror=unused-variable]
 static pthread_t sCurrentSceneThread;
                  ^~~~~~~~~~~~~~~~~~~
src/rtScriptNode/rtWrapperUtils.cpp:21:24: error: ‘sSceneLock’ defined but not used [-Werror=unused-variable]
 static pthread_mutex_t sSceneLock = PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP;
                        ^~~~~~~~~~